In [1]:
from data.helper import *

In [2]:
DF = get_train_df()

100%|██████████| 120/120 [00:00<00:00, 3314.24it/s]

In [3]:
for metric in ["n_colours", "mse_loss", "f1_macro"]:
    print(metric)
    df = DF.copy()
    df = df[df.iterations == "4"]
    df = df[df.completed]
    df = df[df["optimiser"].isin({"svr", "rank-svm", "gpr", "rank-gpc"})]
    # combine rows with same pruning, optimiser and iterations
    df = df.groupby(["pruning", "optimiser", "domain"]).max().reset_index()
    df = df[["pruning", "optimiser", "domain", metric]]
    # pivot table
    df = df.pivot_table(index=["optimiser", "pruning"], values=metric, columns="domain")
    # make entries int2
    if metric == "n_colours":
        df = df.fillna(0)
        df = df.astype(int)
    display(df)

n_colours

domain                    blocksworld  childsnack  ferry  floortile  miconic  \
optimiser pruning
gpr       collapse-all           3218         105   1507       5444       20
          collapse-layer         1771          86    203        757       28
          none                  10445         255   3232       7620      112
rank-gpc  collapse-all          10506         123   2373          0        0
          collapse-layer         3577          96    217          0        0
          none                  22836         263   4398          0        0
rank-svm  collapse-all          10506         123   2373      13380       20
          collapse-layer         3577          96    217       2262       28
          none                  22836         263   4398          0      112
svr       collapse-all           3218         105   1507       5444       20
          collapse-layer         1771          86    203        757       28
          none                  10445         255   3232       7620      112

domain                    rovers  satellite  sokoban  spanner  transport
optimiser pruning
gpr       collapse-all      4529       5232       22      189       2255
          collapse-layer    4583       5938       30      103       1295
          none             23206      22159      114      354       3791
rank-gpc  collapse-all         0          0       27      208       6545
          collapse-layer       0          0       30      106       3129
          none                 0          0      118      378       8936
rank-svm  collapse-all     18808          0       27      208       6545
          collapse-layer   13947          0       30      106       3129
          none                 0          0      118      378       8936
svr       collapse-all      4529       5232       22      189       2255
          collapse-layer    4583       5938       30      103       1295
          none             23206      22159      114      354       3791

mse_loss

domain                    blocksworld  childsnack     ferry  floortile  \
optimiser pruning
gpr       collapse-all       1.131817    0.335210  0.017123   0.476164
          collapse-layer     0.047142    0.335213  0.036962   0.656798
          none               1.167437    0.335210  0.017123   0.476164
rank-gpc  collapse-all      -1.000000   -1.000000 -1.000000        NaN
          collapse-layer    -1.000000   -1.000000 -1.000000        NaN
          none              -1.000000   -1.000000 -1.000000        NaN
rank-svm  collapse-all      -1.000000   -1.000000 -1.000000  -1.000000
          collapse-layer    -1.000000   -1.000000 -1.000000  -1.000000
          none              -1.000000   -1.000000 -1.000000        NaN
svr       collapse-all       0.000421    1.308301  0.049911   0.646432
          collapse-layer     0.091440    0.862840  0.100699   0.803673
          none               0.004935    0.574822  0.044637   0.644310

domain                     miconic    rovers  satellite    sokoban   spanner  \
optimiser pruning
gpr       collapse-all    0.748819  0.134613   0.014584  49.854749  1.585992
          collapse-layer  0.748819  0.136321   0.017880  50.229617  1.592559
          none            0.748819  0.134613   0.014584  49.868695  1.585992
rank-gpc  collapse-all         NaN       NaN        NaN  -1.000000 -1.000000
          collapse-layer       NaN       NaN        NaN  -1.000000 -1.000000
          none                 NaN       NaN        NaN  -1.000000 -1.000000
rank-svm  collapse-all   -1.000000 -1.000000        NaN  -1.000000 -1.000000
          collapse-layer -1.000000 -1.000000        NaN  -1.000000 -1.000000
          none           -1.000000       NaN        NaN  -1.000000 -1.000000
svr       collapse-all    0.763184  0.201610   2.678003  67.467223  1.662510
          collapse-layer  0.769398  0.186038   3.351806  52.498732  1.700438
          none            0.761053  0.230729   2.686692  57.124089  1.671015

domain                    transport
optimiser pruning
gpr       collapse-all     0.048486
          collapse-layer   0.089621
          none             0.048486
rank-gpc  collapse-all    -1.000000
          collapse-layer  -1.000000
          none            -1.000000
rank-svm  collapse-all    -1.000000
          collapse-layer  -1.000000
          none            -1.000000
svr       collapse-all     0.084458
          collapse-layer   0.129761
          none             0.084280

f1_macro

domain                    blocksworld  childsnack     ferry  floortile  \
optimiser pruning
gpr       collapse-all       1.000000    0.598779  0.998266   0.508062
          collapse-layer     0.970538    0.598779  0.987128   0.368957
          none               1.000000    0.599810  0.998266   0.509689
rank-gpc  collapse-all      -1.000000   -1.000000 -1.000000        NaN
          collapse-layer    -1.000000   -1.000000 -1.000000        NaN
          none              -1.000000   -1.000000 -1.000000        NaN
rank-svm  collapse-all      -1.000000   -1.000000 -1.000000  -1.000000
          collapse-layer    -1.000000   -1.000000 -1.000000  -1.000000
          none              -1.000000   -1.000000 -1.000000        NaN
svr       collapse-all       1.000000    0.204988  0.948551   0.647532
          collapse-layer     0.952579    0.249039  0.904542   0.479013
          none               1.000000    0.263305  0.949564   0.648506

domain                     miconic    rovers  satellite   sokoban   spanner  \
optimiser pruning
gpr       collapse-all    0.350867  0.876946   0.968744  0.022827  0.277272
          collapse-layer  0.351951  0.872159   0.967466  0.022696  0.270121
          none            0.350867  0.876865   0.968740  0.022200  0.277272
rank-gpc  collapse-all         NaN       NaN        NaN -1.000000 -1.000000
          collapse-layer       NaN       NaN        NaN -1.000000 -1.000000
          none                 NaN       NaN        NaN -1.000000 -1.000000
rank-svm  collapse-all   -1.000000 -1.000000        NaN -1.000000 -1.000000
          collapse-layer -1.000000 -1.000000        NaN -1.000000 -1.000000
          none           -1.000000       NaN        NaN -1.000000 -1.000000
svr       collapse-all    0.351767  0.902183   0.000283  0.013068  0.302128
          collapse-layer  0.352187  0.898595   0.000283  0.021333  0.288699
          none            0.359890  0.894678   0.000285  0.014972  0.299427

domain                    transport
optimiser pruning
gpr       collapse-all     0.926999
          collapse-layer   0.922267
          none             0.926986
rank-gpc  collapse-all    -1.000000
          collapse-layer  -1.000000
          none            -1.000000
rank-svm  collapse-all    -1.000000
          collapse-layer  -1.000000
          none            -1.000000
svr       collapse-all     0.923425
          collapse-layer   0.906617
          none             0.921788

In [4]:
for domain in DOMAINS:
    df = DF.copy()
    print(domain)
    df = df[df["domain"] == domain]
    df = df[df["optimiser"].isin({"svr", "rank-svm"})]
    # combine rows with same pruning, optimiser and iterations
    df = df.groupby(["pruning", "optimiser"]).max().reset_index()
    df = df[["pruning", "optimiser", "n_data"]]
    # pivot table
    df = df.pivot_table(index=["pruning", "optimiser"], values="n_data")
    # make entries int2
    df = df.astype(int)
    df = df.fillna(0)
    display(df)

blocksworld

                          n_data
pruning        optimiser
collapse-all   rank-svm     7703
               svr          1292
collapse-layer rank-svm     7703
               svr          1292
none           rank-svm     7703
               svr          1292

childsnack

                          n_data
pruning        optimiser
collapse-all   rank-svm    10334
               svr           473
collapse-layer rank-svm    10334
               svr           473
none           rank-svm    10334
               svr           473

ferry

                          n_data
pruning        optimiser
collapse-all   rank-svm    13719
               svr          1368
collapse-layer rank-svm    13719
               svr          1368
none           rank-svm    13719
               svr          1368

floortile

                          n_data
pruning        optimiser
collapse-all   rank-svm    32549
               svr          3187
collapse-layer rank-svm    32549
               svr          3187
none           rank-svm       -1
               svr          3187

miconic

                          n_data
pruning        optimiser
collapse-all   rank-svm    24089
               svr          1630
collapse-layer rank-svm    24089
               svr          1630
none           rank-svm    24089
               svr          1630

rovers

                          n_data
pruning        optimiser
collapse-all   rank-svm    21036
               svr          1428
collapse-layer rank-svm    21036
               svr          1428
none           rank-svm       -1
               svr          1428

satellite

                          n_data
pruning        optimiser
collapse-all   rank-svm       -1
               svr          1158
collapse-layer rank-svm       -1
               svr          1158
none           rank-svm       -1
               svr          1158

sokoban

                          n_data
pruning        optimiser
collapse-all   rank-svm    10406
               svr          2422
collapse-layer rank-svm    10406
               svr          2422
none           rank-svm    10406
               svr          2422

spanner

                          n_data
pruning        optimiser
collapse-all   rank-svm     4576
               svr          1204
collapse-layer rank-svm     4576
               svr          1204
none           rank-svm     4576
               svr          1204

transport

                          n_data
pruning        optimiser
collapse-all   rank-svm    15013
               svr           735
collapse-layer rank-svm    15013
               svr           735
none           rank-svm    15013
               svr           735

In [5]:
for domain in DOMAINS:
    df = DF.copy()
    print(domain)
    df = df[df["domain"] == domain]
    df = df[df["optimiser"].isin({"svr", "rank-svm"})]
    # combine rows with same pruning, optimiser and iterations
    df = df.groupby(["pruning", "optimiser", "iterations"]).max().reset_index()
    df = df[["pruning", "optimiser", "iterations", "n_colours"]]
    # pivot table
    df = df.pivot_table(index=["pruning", "optimiser"], columns="iterations", values="n_colours")
    # make entries int
    df = df.astype(int)
    df = df.fillna(0)
    display(df)

blocksworld

iterations                    4
pruning        optimiser
collapse-all   rank-svm   10506
               svr         3218
collapse-layer rank-svm    3577
               svr         1771
none           rank-svm   22836
               svr        10445

childsnack

iterations                  4
pruning        optimiser
collapse-all   rank-svm   123
               svr        105
collapse-layer rank-svm    96
               svr         86
none           rank-svm   263
               svr        255

ferry

iterations                   4
pruning        optimiser
collapse-all   rank-svm   2373
               svr        1507
collapse-layer rank-svm    217
               svr         203
none           rank-svm   4398
               svr        3232

floortile

iterations                    4
pruning        optimiser
collapse-all   rank-svm   13380
               svr         5444
collapse-layer rank-svm    2262
               svr          757
none           rank-svm      -1
               svr         7620

miconic

iterations                  4
pruning        optimiser
collapse-all   rank-svm    20
               svr         20
collapse-layer rank-svm    28
               svr         28
none           rank-svm   112
               svr        112

rovers

iterations                    4
pruning        optimiser
collapse-all   rank-svm   18808
               svr         4529
collapse-layer rank-svm   13947
               svr         4583
none           rank-svm      -1
               svr        23206

satellite

iterations                    4
pruning        optimiser
collapse-all   rank-svm      -1
               svr         5232
collapse-layer rank-svm      -1
               svr         5938
none           rank-svm      -1
               svr        22159

sokoban

iterations                  4
pruning        optimiser
collapse-all   rank-svm    27
               svr         22
collapse-layer rank-svm    30
               svr         30
none           rank-svm   118
               svr        114

spanner

iterations                  4
pruning        optimiser
collapse-all   rank-svm   208
               svr        189
collapse-layer rank-svm   106
               svr        103
none           rank-svm   378
               svr        354

transport

iterations                   4
pruning        optimiser
collapse-all   rank-svm   6545
               svr        2255
collapse-layer rank-svm   3129
               svr        1295
none           rank-svm   8936
               svr        3791